name: Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        run: |
          cd /home/gshorti/src/krutoy-toose
          git pull
          docker build -t krutoi-toose .
          docker run -d -p 6767:80 krutoi-toose:latest
